[package]
name = "fooshot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
hyprland = "0.4.0-beta.1"
image = "0.25"
tempfile = "3.21"
which = "8.0.0"
